apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: definitions.oam.stacks.crossplane.io
spec:
  preserveUnknownFields: true
  group: oam.stacks.crossplane.io
  names:
    kind: Definitions
    listKind: DefinitionsList
    plural: definitions
    singular: definitions
  scope: Cluster
  subresources:
    status: {}
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []